# Site settings
title: On the Road
email: aichaowang@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    他是个二货^_^
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ulyssess.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  ulyssess

# Build settings
markdown: kramdown
